name: immortality
'on':
  schedule:
  - cron: 0 2 1 * *
  workflow_dispatch: {}
jobs:
  keepalive:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1
    - name: Keep workflows alive
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_KEEPALIVE_TOKEN }}
        REPOS: ${{ github.repository }}
      run: |
        test "$(gh api user --jq '.login + "/" + (.id|tostring)')" = edbfi/326875205
        bash ./scripts/vendor/gh-workflow-immortality.sh
    if: github.repository == 'edbfi/homebrew-taps' && github.ref_name == github.event.repository.default_branch
    timeout-minutes: 10
permissions:
  contents: read
concurrency:
  group: keepalive
  cancel-in-progress: false
